### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by romw** [BOINC/boinc-ng#241]
**Reported by elfring on 12 Aug 37431071 20:00 UTC**
The following functions do not belong to the list of async-signal-safe functions. (See section "[ 2.4.3 Signal Actions](http://opengroup.org/onlinepubs/009695399/functions/xsh_chap02_04.html#tag_02_04_03)" from the document "2.4 Signal Concepts".)[fprintf()[[BR]([BR]]
-)]
- getrusage()[longjmp()[[BR]([BR]]
-)]
- perror()[pthread_equal()[[BR]([BR]]
-)]
- pthread_mutex_trylock()[pthread_mutex_unlock()

Should the corresponding calls be replaced by safe alternatives in your functions "[source:/trunk/boinc/api/boinc_api.C@12324#L808 worker_signal_handler]([BR]]
-)" and "[restart_sig](source:/trunk/boinc/api/x_opengl.C@11619#L539)"?

How do you think about to specify the data type "sig_atomic_t" for the variables "options.direct_process_action", "boinc_status.suspended" and "in_critical_section"?

**Comment by romw** [comment]
**Commented by davea on 9 Feb 38425627 00:26 UTC**
None of those functions are used in signal handlers anymore

**Comment by elfring** [comment]
[The function "restart_sig"](https://github.com/BOINC/boinc/blob/5858534492902c1e215a74eda15b0b734109e12a/api/x_opengl.cpp#L553 "Check signal handling implementation.") calls still functions which are async-signal-unsafe.
Can this implementation be improved?
