### ISSUE TITLE
Usage of sane build system

### ISSUE THREAD

**Issue by romw** [BOINC/boinc-ng#887]
**Reported by scarabeus on 9 Mar 39424028 23:06 UTC**
Hello,
I am gentoo maintainer of boinc package currently and the new version fails me again in several ways (usage of internal libs, automagicness, etc.).

So I would like to ask you if you would accept cmake-based build system based on some branch you have or trunk, what ever would be best.

Why cmake? Because i am one of cmake maintainer too so i am quite solid there and in autotools i am not that good :]
So i am definetly sure i could be able to write the cmake system, but I need to know if it is worth doing, you accept it, or i should keep whacking the autotools pretty badly with each release.

For starters i am capable of writing the linux build on it, where since cmake is multiplatform it should be quite easy to port it to osx and windows.

For simple example how cmake build system looks please point your eyes to http://repo.or.cz/w/tuxanci.git where i am trying to write simple and easy to understand build structure in cmake, so others can copy/learn from it.

Cheers

**Comment by romw** [comment]
**Commented by Nicolas on 23 Sep 39424396 10:40 UTC**
I have a CMake build system for the client here:
http://synecdoche.googlecode.com/svn/branches/cmake/

Untested for a long while, and won't work directly for BOINC (because all server code is removed from there). And only seriously tested in Linux, did few tests on Windows, and didn't work on Mac. And it's based on old code (there may be new .cpp files to add by now).

I also wrote a ```CMakeLists.txt``` for the server code (also standalone, with client code removed). It compiles, but doesn't leave files where ```make_project``` expects them, so it doesn't really "work". And it's not publicly available at the moment.

Either way, I don't think it will be so easy for you to convince BOINC devs to completely switch build systems ;)

**Comment by romw** [comment]
**Commented by scarabeus on 8 Apr 39426609 20:53 UTC**
That is the reason why i am asking, i can write something, but definetly i wont test all features, so i would like to know devs opinion if they are interested.
Packaging current boinc is quite big pita so anything that improves it will make me happy.

**Comment by romw** [comment]
**Commented by korpela on 26 Apr 39427073 14:40 UTC**

"but definetly i wont test all features" is probably the reason I'll say no.  You also probably aren't willing to test it on flavors of BSD, Solaris, and other assorted operating systems.  If you were volunteering to take over maintenance of the build system, I'd say go for it.  As proposed, it's just throwing an incomplete build system I don't have any experience with in my lap and calling it an improvement.

**Comment by skybon** [comment]
I'd be willing to give CMake a spin and even test it on obscure platforms if necessary. Don't know if the porting should be made before or after #1551.
